### ISSUE TITLE
[feature request] Override for "AppDomainFriendlyName"

### ISSUE THREAD

**Issue by jeoffman** [amccool/AM.Elasticsearch.TraceListener#19]
We are using this in an IIS Web App and a Windows Service. The AppDomainFriendlyName for the Windows Service looks great, but the one for the Web App looks like:
/LM/W3SVC/1039/ROOT-1-131631189689932306

It would be nice if the AppDomainFriendlyName was the name of the web app, or if I could override it with my own custom (useful) text.

**Comment by amccool** [comment]
refer to index aliases and field mappings
