### ISSUE TITLE
How to pass username , password and headers?

### ISSUE THREAD

**Issue by woeterman94** [amccool/AM.Elasticsearch.TraceListener#23]
How can I pass authorization headers to kibana?

**Comment by amccool** [comment]
@woeterman94 currently the way to do authentication is to use the Uri passed in to have a username/password in the Uri.    Obviously not optimal.   Do you have a PR for the necessary code to add the headers?

BTW - your referring to Elasticsearch, not Kibana, right?   as this only posts to Elasticsearch not kibana

**Comment by amccool** [comment]
no return comment (but its valid)
