### ISSUE TITLE
Handle serializing objects that can throw during serialization

### ISSUE THREAD

**Issue by jeoffman** [amccool/AM.Elasticsearch.TraceListener#25]
using TraceData on some EntityFramework exceptions cause the ES TraceListener serializer to throw.

The original exception was a DbEntityValidationException, which caused the TraceData to throw a JsonSerializationException due to a "Self referencing loop".

Another Entity Framework Error was: "OriginalValues cannot be used for entities in the Added state" appeared to be trying to serialize properties of the EF entities which seem to be throwing during the property's "get".

Under both cases our ILogger was catching the exception thrown by Elasticsearch.TraceListener but the messages were not very useful.

I will have a pull request ready in just a minute

**Comment by amccool** [comment]
I think you got it @jeoffman 
reopen if it still exists
